# Generated by Django 2.2 on 2020-03-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('precioChiper', models.FloatField()),
                ('precioTienda', models.FloatField()),
                ('codigo', models.IntegerField()),
                ('catidad', models.IntegerField()),
                ('fechaDeVencimiento', models.DateField()),
                ('tienda', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.Tienda')),
            ],
        ),
    ]
