# Generated by Django 2.2 on 2020-03-21 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20200321_1840'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ventas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='venta.Venta'),
        ),
    ]
