# Generated by Django 2.2 on 2020-03-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ventas',
        ),
    ]
