# Generated by Django 2.2 on 2020-03-21 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
        ('deudor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudor',
            name='id',
        ),
        migrations.AddField(
            model_name='deudor',
            name='tienda',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tienda.Tienda'),
        ),
    ]
