# Generated by Django 3.0.3 on 2020-03-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('contrasena', models.CharField(max_length=60)),
                ('identificacion', models.IntegerField()),
                ('numeroCelular', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
            ],
        ),
    ]
