# Generated by Django 3.0.3 on 2020-03-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncargadoOperacion',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
                ('cargo', models.CharField(max_length=60)),
                ('nivel', models.CharField(max_length=60)),
            ],
            bases=('usuarios.usuario',),
        ),
    ]
