# Generated by Django 3.0.3 on 2020-03-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_encargadooperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
                ('licencia', models.IntegerField()),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='EncargadoLogistico',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
                ('experiencia', models.CharField(max_length=60)),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Tendero',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
                ('RUT', models.IntegerField()),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('tendero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Tendero')),
            ],
            bases=('usuarios.tendero',),
        ),
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('administrador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Administrador')),
            ],
            bases=('usuarios.administrador',),
        ),
        migrations.CreateModel(
            name='CTO',
            fields=[
                ('administrador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Administrador')),
            ],
            bases=('usuarios.administrador',),
        ),
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('tendero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Tendero')),
            ],
            bases=('usuarios.tendero',),
        ),
    ]
