# Generated by Django 3.0.6 on 2020-05-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_administrador_cajero_ceo_conductor_cto_dueño_encargadologistico_tendero'),
    ]

    operations = [
        migrations.AddField(
            model_name='dueño',
            name='nada',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
