# Generated by Django 3.0.6 on 2020-05-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_dueño_nada'),
    ]

    operations = [
        migrations.AddField(
            model_name='dueño',
            name='nada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
