# Generated by Django 3.0.6 on 2020-05-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_dueño_nada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dueño',
            name='nada',
        ),
    ]
