# Generated by Django 3.0.6 on 2020-05-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_dueño_nada'),
    ]

    operations = [
        migrations.AddField(
            model_name='dueño',
            name='nada',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
