# Generated by Django 2.2 on 2020-03-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valor', models.FloatField()),
                ('fechaVenta', models.DateField()),
                ('tipoPago', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Tienda',
        ),
    ]
