# Generated by Django 2.2 on 2020-03-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='empezado', max_length=60),
            preserve_default=False,
        ),
    ]
